Add python script to import storybooks
elimu-ai/ml-storybook-reading-level pull request #7
Opened 2024-08-06 23:42 UTC by SnehaHS65

Refs #174
 
#1 to import story book dataset

2024-08-07 01:16 UTC, jo-elimu approved these changes
Looks good, @SnehaHS65 🙂

It's probably better if we use the dataset from the `PROD` environment, since the data there will be more up-to-date and more accurate.

2024-08-07 01:16 UTC, jo-elimu commented on prepare_data.py
> +ENVIRONMENT = "TEST"
```suggestion
ENVIRONMENT = "PROD"
```

2024-08-07 02:20 UTC, nya-elimu commented
@coderabbitai

2024-08-08 03:40 UTC, jo-elimu commented on env-TEST/lang-HIN/data/storybooks.csv
@SnehaHS65 With the change from `TEST` to `PROD`, this CSV file probably needs to be replaced?

2024-08-08 03:42 UTC, jo-elimu requested changes
Replace the folder name `env-TEST/` with `env-PROD/` (and replace the CSV file itself).

2024-08-08 13:21 UTC, SnehaHS65 commented on env-TEST/lang-HIN/data/storybooks.csv
@jo-elimu , I took the dataset from https://github.com/elimu-ai/webapp/blob/main/src/main/resources/db/content_PROD/hin/storybooks.csv.
Isn't this the prod one?

2024-08-08 15:32 UTC, jo-elimu commented on env-TEST/lang-HIN/data/storybooks.csv
Yes, that's right. But the file was stores within a `TEST` folder in this repo. And I see that was fixed now, in the latest commit 👍

2024-08-08 15:32 UTC, jo-elimu approved these changes

2024-08-08 15:34 UTC, merged